-- ==========================================================================
-- SCRIPT DE INSTALACION Y MIGRACION: MODULO GUIAS DE DESPACHO (PROCLEANMG)
-- Ejecutar este script completo en el Editor SQL de Supabase
-- ==========================================================================

-- 1. TABLA MAESTRA DE GUIAS DE DESPACHO
CREATE TABLE IF NOT EXISTS guias_despacho (
    id BIGSERIAL PRIMARY KEY,
    folio INTEGER UNIQUE NOT NULL,
    fecha DATE NOT NULL,
    hora TEXT DEFAULT '09:00',
    razon_social TEXT DEFAULT 'ProCleanMG SpA',
    rut_empresa TEXT DEFAULT '76801700-K',
    telefono_empresa TEXT DEFAULT '934068272',
    correo_empresa TEXT DEFAULT 'mandrade@procleanmg.cl',
    direccion_empresa TEXT DEFAULT 'Procleanmg',
    emisor_nombre TEXT DEFAULT 'Marco Andrade',
    emisor_rut TEXT DEFAULT '18276074-9',
    emisor_domicilio TEXT DEFAULT 'Av. Iquique 3115',
    emisor_ciudad TEXT DEFAULT 'Antofagasta',
    emisor_comuna TEXT DEFAULT 'Antofagasta',
    emisor_telefono TEXT DEFAULT '934068272',
    transportista_nombre TEXT,
    vehiculo TEXT,
    patente TEXT,
    chofer TEXT,
    lugar_entrega TEXT NOT NULL,
    observaciones TEXT,
    estado TEXT NOT NULL DEFAULT 'PENDIENTE', -- PENDIENTE, EN_TRANSITO, ENTREGADA, ANULADA
    motivo_anulacion TEXT,
    receptor_nombre TEXT,
    receptor_rut TEXT,
    receptor_fecha TEXT,
    firma_digital TEXT,
    foto_comprobante TEXT,
    created_by TEXT DEFAULT 'Operador',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABLA DE ITEMS / CARGA DE LA GUIA
CREATE TABLE IF NOT EXISTS guia_despacho_items (
    id BIGSERIAL PRIMARY KEY,
    guia_id BIGINT NOT NULL REFERENCES guias_despacho(id) ON DELETE CASCADE,
    articulo TEXT,
    descripcion TEXT NOT NULL,
    cantidad NUMERIC NOT NULL DEFAULT 1,
    unidad TEXT DEFAULT 'UN',
    observacion TEXT
);

-- 3. TABLA DE AUDITORIA Y TRAZABILIDAD
CREATE TABLE IF NOT EXISTS guias_despacho_audit (
    id BIGSERIAL PRIMARY KEY,
    guia_id BIGINT,
    folio INTEGER,
    accion TEXT NOT NULL,
    usuario TEXT DEFAULT 'Operador',
    detalles TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABLA DE CATALOGOS (VEHICULOS, CHOFERES, DESTINOS)
CREATE TABLE IF NOT EXISTS guias_despacho_catalogos (
    id BIGSERIAL PRIMARY KEY,
    tipo TEXT NOT NULL,
    nombre TEXT NOT NULL,
    frecuencia INTEGER DEFAULT 1,
    UNIQUE(tipo, nombre)
);

-- 5. TABLA DE CONFIGURACION
CREATE TABLE IF NOT EXISTS guias_despacho_config (
    clave TEXT PRIMARY KEY,
    valor TEXT
);

-- HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE guias_despacho ENABLE ROW LEVEL SECURITY;
ALTER TABLE guia_despacho_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE guias_despacho_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE guias_despacho_catalogos ENABLE ROW LEVEL SECURITY;
ALTER TABLE guias_despacho_config ENABLE ROW LEVEL SECURITY;

-- POLITICAS RLS (Lectura, Insercion, Modificacion y Eliminacion)
DROP POLICY IF EXISTS "Acceso total guias_despacho" ON guias_despacho;
CREATE POLICY "Acceso total guias_despacho" ON guias_despacho FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total guia_despacho_items" ON guia_despacho_items;
CREATE POLICY "Acceso total guia_despacho_items" ON guia_despacho_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total guias_despacho_audit" ON guias_despacho_audit;
CREATE POLICY "Acceso total guias_despacho_audit" ON guias_despacho_audit FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total guias_despacho_catalogos" ON guias_despacho_catalogos;
CREATE POLICY "Acceso total guias_despacho_catalogos" ON guias_despacho_catalogos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total guias_despacho_config" ON guias_despacho_config;
CREATE POLICY "Acceso total guias_despacho_config" ON guias_despacho_config FOR ALL USING (true) WITH CHECK (true);

-- 6. POBLADO DE CONFIGURACION INICIAL
INSERT INTO guias_despacho_config (clave, valor) VALUES ('empresa_razon_social', 'ProCleanMG SPA') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('empresa_rut', '76801700-K') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('empresa_telefono', '934068272') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('empresa_correo', 'mandrade@procleanmg.cl') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('empresa_direccion', 'Procleanmg') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('emisor_nombre', 'Marco Andrade') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('emisor_rut', '18276074-9') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('emisor_domicilio', 'Av. Iquique 3115') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('emisor_ciudad', 'Antofagasta') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('emisor_comuna', 'Antofagasta') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;
INSERT INTO guias_despacho_config (clave, valor) VALUES ('emisor_telefono', '934068272') ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor;

-- 7. POBLADO DE CATALOGOS INICIALES
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('vehiculo', 'Maxus T60') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('vehiculo', 'Toyota Hilux') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('vehiculo', 'Mitsubishi L200') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('vehiculo', 'Volkswagen Delivery') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('vehiculo', 'Camión Hino SCBY16') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('vehiculo', 'Hyundai Porter') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('vehiculo', 'Shineray T50') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('vehiculo', 'Bus Yutong') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('vehiculo', 'Grúa Rescate') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'PWM Chile') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'Oficina ANT') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'Taller GMI') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'Kaufman') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'Derco') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'MPM') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'Salmos sur 107') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'Av. Argentina 2309') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'Av. José Infante, Salamanca') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'Faena Minera') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('destino', 'Faena Zaldívar') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Marco Andrade') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Luis Gamboa') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Pedro Velazquez') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Robert Gonzalez') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Manuel Espinosa') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Santos Jofre') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Alexis Silva') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Bruno Castro') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Ignacio Perez') ON CONFLICT (tipo, nombre) DO NOTHING;
INSERT INTO guias_despacho_catalogos (tipo, nombre) VALUES ('chofer', 'Jhon Diaz') ON CONFLICT (tipo, nombre) DO NOTHING;

-- 8. MIGRACION DE GUIAS HISTORICAS (41 FOLIOS)
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (1, 2, '2024-08-29', '09:00', 'Aseo IndustriaL', '18276074-9', '56934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Robert Gonzalez', '18276074-9', 'Salmos sur 107', 'Santiago', 'Maipu', '56934068272', 'Robert', 'Maxus T60', NULL, 'Robert', 'Antofagasta', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (2, 3, '2024-08-27', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Samuel Velasquez', '18793152-5', 'Av. Argentina 2309', 'Antofagasta', 'Antofagasta', '940745844', 'Samuel Velasquez', 'Maxus T60', NULL, 'Chofer de Turno', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (3, 4, '2024-08-28', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '18793152-5', 'Av. Argentina 2309', 'Antofagasta', 'Antofagasta', '940745844', 'Luis G', 'Maxus T60', NULL, 'Luis G', 'Taller GMI', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (4, 5, '2024-08-28', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Juan Valdez', '18793152-5', 'Av. Argentina 2309', 'Antofagasta', 'Antofagasta', '940745844', 'Juan V', 'grua rescate', NULL, 'Juan V', 'kaufman', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (5, 6, '2024-08-05', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '18793152-5', 'Av. Argentina 2309', 'Antofagasta', 'Antofagasta', '940745844', 'Luis G', 'Maxus T60', NULL, 'Luis G', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (6, 7, '2024-08-17', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '18793152-5', 'Av. Argentina 2309', 'Antofagasta', 'Antofagasta', '940745844', 'Luis G', 'Maxus T60', NULL, 'Luis G', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (7, 8, '2024-10-01', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '18793152-5', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '940745844', 'Luis G', 'Maxus T60', NULL, 'Luis G', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (8, 9, '2024-11-05', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Santos Jofre', '18793152-5', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '940745844', 'Santos Jofre', 'Kia frontier', NULL, 'Santos Jofre', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (9, 10, '2024-11-06', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Luis Vila', '18793152-5', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '940745844', 'Luis Vila', 'SINOTRUK', NULL, 'Luis Vila', 'Derco', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (10, 11, '2024-11-14', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Pedro Velazquez', '18793152-5', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '940745844', 'Pedro Velazquez', 'Equipo interno', NULL, 'Pedro Velazquez', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (11, 12, '2026-09-29', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Pedro Velazquez', '18793152-5', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '940745844', 'Pedro Velazquez', 'Equipo interno', NULL, 'Pedro Velazquez', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (12, 13, '2024-12-10', '09:00', 'Aseo IndustriaL', '18793152-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '18793152-5', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '940745844', 'Luis Gamboa', 'Maxus T60', NULL, 'Luis Gamboa', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (13, 14, '2024-12-10', '09:00', 'Aseo IndustriaL', '187931525-5', '940745844', 'rgonzalez@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '187931525-5', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '940745844', 'Luis Gamboa', 'Maxus T60', NULL, 'Luis Gamboa', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (14, 15, '2024-12-24', '09:00', 'Aseo IndustriaL', '18276074-9', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Alexis Silva', '18276074-9', 'Salmos sur 107', 'Santiago', 'Maipu', '934068272', 'Alexis Silva', 'Maxus T60', NULL, 'Alexis Silva', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (15, 16, '2024-12-24', '09:00', 'Aseo IndustriaL', '18276074-9', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '18276074-9', 'Salmos sur 107', 'Santiago', 'Maipu', '934068272', 'Luis G', 'Maxus T60', NULL, 'Luis G', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (16, 17, '2025-01-21', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Pedro Velazquez', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Pedro Velazquez', 'Maxus T60', NULL, 'Pedro Velazquez', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (17, 18, '2025-01-21', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Luis Gamboa', 'Maxus T60', NULL, 'Luis Gamboa', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (18, 19, '2025-02-04', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Robert Gonzalez', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Robert Gonzalez', 'Maxus T60', NULL, 'Robert Gonzalez', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (19, 20, '2025-02-04', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Manuel Espinosa', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Manuel Espinosa', 'Maxus T60', NULL, 'Manuel Espinosa', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (20, 21, '2025-02-12', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Marco andrade', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Marco andrade', 'Mitsubichi L200', NULL, 'Marco andrade', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (21, 22, '2025-02-19', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Robert Gonzalez', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Robert Gonzalez', 'Maxus T60', NULL, 'Robert Gonzalez', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (22, 23, '2025-04-08', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Marco Zepeda', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Marco Zepeda', 'Volkswagen Delivery', NULL, 'Marco Zepeda', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (23, 24, '2025-05-07', '09:00', 'Aseo IndustriaL', '76801700-K', '940745844', 'mandrade@procleanmg.cl', 'Procleanmg', 'Alberto López', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '940745844', 'PDQ', 'PDQ', NULL, 'PDQ', 'Av. José Infante, Salamanca', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (24, 25, '2025-05-08', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Luis Gamboa', 'grua rescate', NULL, 'Luis Gamboa', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (25, 26, '2025-05-14', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Jhon Diaz', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Luis Gamboa', 'Camion Hino SCBY16', NULL, 'Luis Gamboa', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (26, 27, '2025-05-20', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Jhon Diaz', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Jhon Diaz', 'Camion Hino SCBY16', NULL, 'Jhon Diaz', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (27, 28, '2025-05-27', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Alexis Silva', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Alexis Silva', 'Hyundai porter', NULL, 'Alexis Silva', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (28, 29, '2025-05-29', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Marco andrade', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Marco andrade', 'Toyota Hilux', NULL, 'Marco andrade', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (29, 30, '2025-06-02', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Ignacio Perez', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Ignacio Perez', 'Mitsibichi L200', NULL, 'Ignacio Perez', 'MPM', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (30, 31, '2025-06-04', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Luis Gamboa', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Luis Gamboa', 'Toyota Hilux', NULL, 'Luis Gamboa', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (31, 32, '2025-06-18', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Raisin', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Raisin', 'Bus Yutong', NULL, 'Raisin', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (32, 33, '2025-06-19', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Jorge Antonio', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Jorge Antonio', 'Tracto camion international', NULL, 'Jorge Antonio', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (33, 34, '2025-07-02', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Santos Jofre', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Santos Jofre', 'Mitsibichi L200', NULL, 'Santos Jofre', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (34, 35, '2025-07-08', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Juan Mamani', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Juan Mamani', 'Toyota Hilux', NULL, 'Juan Mamani', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (35, 36, '2025-07-15', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'John Diaz', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'John Diaz', 'Camion Hino XZU 917', NULL, 'John Diaz', 'PWM Chile', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (36, 37, '2025-07-15', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'John Diaz', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'John Diaz', 'Camion Hino XZU 917', NULL, 'John Diaz', 'MPM', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (37, 38, '2025-07-22', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Manuel Espinosa', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Manuel Espinosa', 'Toyota Hilux', NULL, 'Manuel Espinosa', 'Oficina ANT', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (38, 39, '2025-12-29', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Bruno Castro', '76801700-K', 'Av. Iquique 3114', 'Antofagasta', 'Antofagasta', '934068272', 'Bruno Castro', 'Shineray T50', NULL, 'Bruno Castro', 'PWM Chile', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (39, 40, '2025-12-30', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Bruno Castro', '76801700-K', 'Av. Iquique 3115', 'Antofagasta', 'Antofagasta', '934068272', 'Bruno Castro', 'Shineray T51', NULL, 'Bruno Castro', 'PWM Chile', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (40, 41, '2026-01-12', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Ignacio Perez', '76801700-K', 'Av. Iquique 3115', 'Antofagasta', 'Antofagasta', '934068272', 'Ignacio Perez', 'Mitsubichi L200', NULL, 'Ignacio Perez', 'PWM Chile', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;
INSERT INTO guias_despacho (id, folio, fecha, hora, razon_social, rut_empresa, telefono_empresa, correo_empresa, direccion_empresa, emisor_nombre, emisor_rut, emisor_domicilio, emisor_ciudad, emisor_comuna, emisor_telefono, transportista_nombre, vehiculo, patente, chofer, lugar_entrega, observaciones, estado, receptor_nombre, receptor_rut, created_by) VALUES (41, 42, '2026-02-05', '09:00', 'Aseo IndustriaL', '76801700-K', '934068272', 'mandrade@procleanmg.cl', 'Procleanmg', 'Ignacio Perez', '76801700-K', 'Av. Iquique 3115', 'Antofagasta', 'Antofagasta', '934068272', 'Ignacio Perez', 'Mitsubichi L201', NULL, 'Ignacio Perez', 'PWM Chile', NULL, 'ENTREGADA', NULL, NULL, 'Importación Excel') ON CONFLICT (folio) DO NOTHING;

-- 9. MIGRACION DE ITEMS HISTORICOS
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (1, 1, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (2, 2, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (3, 3, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (4, 4, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (5, 5, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (6, 6, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (7, 7, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (8, 8, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (9, 9, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (10, 10, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (11, 11, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (12, 12, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (13, 13, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (14, 14, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (15, 15, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (16, 16, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (17, 17, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (18, 18, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (19, 19, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (20, 20, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (21, 21, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (22, 22, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (23, 23, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (24, 24, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (25, 25, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (26, 26, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (27, 27, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (28, 28, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (29, 29, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (30, 30, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (31, 31, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (32, 32, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (33, 33, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (34, 34, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (35, 35, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (36, 36, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (37, 37, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (38, 38, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (39, 39, '2', 'Neumáticos 11R22.5', 1.0, 'UN', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (40, 40, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO guia_despacho_items (id, guia_id, articulo, descripcion, cantidad, unidad, observacion) VALUES (41, 41, '1', 'Carga e insumos operativos', 1.0, 'GL', NULL) ON CONFLICT (id) DO NOTHING;

-- 10. AJUSTE DE SECUENCIAS EN POSTGRESQL
SELECT setval('guias_despacho_id_seq', COALESCE((SELECT MAX(id) FROM guias_despacho), 1));
SELECT setval('guia_despacho_items_id_seq', COALESCE((SELECT MAX(id) FROM guia_despacho_items), 1));
SELECT setval('guias_despacho_audit_id_seq', COALESCE((SELECT MAX(id) FROM guias_despacho_audit), 1));
SELECT setval('guias_despacho_catalogos_id_seq', COALESCE((SELECT MAX(id) FROM guias_despacho_catalogos), 1));